    // {
    //     id: ,
    //     title: '',
    //     images: [],
    //     old_price: 0,
    //     price: 0,
    //     description: '',
    //     tags: [],
    //     rating: 0,
    //     carousel: {
    //              today: false, 
    //              week: false,
    //              like: false, 
    //              new: false,
    //              top: false,
    //              recommend: false,
    //            },
    // }

const products =[
    {
        id: 1,
        title: 'Uvex Finale 2.0',
        images: ['helmet-1_1.jpg','helmet-1_2.jpg'],
        old_price: 17999,
        price: 16199,
        description: "Шлем Uvex с удлиненной затылочной частью и съемным козырьком обеспечивает надежную защиту во время катания по бездорожью. 20 вентиляционных отверстий гарантируют отличный воздухообмен для максимального комфорта, а технология FAS и система 3D IAS отвечают за точную посадку по голове. Размер можно регулировать с помощью поворотного кольца.",
        tags: [1,2],
        rating: 5,
        category: 2,
        carousel: {
                today: false,
                week: false,
                like: false,
                new: false,
                top: false,
                recommend: false,
               }, 
    },
    {
        id: 2,
        title: 'Trek Wahoo 2022',
        images: ['bicycle-1_1.jpg','bicycle-1_2.jpg','bicycle-1_3.jpg'],
        old_price: 78000,
        price: 69990,
        description: 'Велосипед, предназначенный для детей в возрасте от пяти до девяти лет с оборудованием начального любительского класса Shimano, 8 скоростей. Технические особенности: алюминиевая рама Alpha Silver Aluminum, жесткая вилка, двойные алюминиевые обода, надежные ободные тормоза Alloy linear-pull. Подходит для обучения и прогулочного катания в городских условиях. Диаметр колес - 20 дюймов. Вес - 8,89 кг.',
        tags: [],
        rating: 7,
        category: 1,
        carousel: {
                today: false,
                week: false,
                like: false,
                new: false,
                top: false,
                recommend: false,
               },
    },
    {
        id: 3,
        title: 'Trek 1120 (2022)',
        images: ['bicycle-3_1.jpg','bicycle-3_2.jpg','bicycle-3_3.jpg'],
        old_price: null,
        price: 209200,
        description: 'Дорожный велосипед класса туринг с оборудованием начального профессионального уровня Shimano, 12 скоростей. Технические особенности: алюминиевая рама Alpha Platinum Aluminum, жесткая карбоновая вилка 1120 HCM, двойные обода 1120 HCM, дисковые гидравлические тормоза Shimano MT4100 , задний и передний багажники. Подходит для туристического и прогулочного катания по различным дорогам и пересеченной местности. Диаметр колес - 28 дюймов. Вес - 14.08 кг.',
        tags: [],
        rating: 1,
        carousel: {
                 today: false, 
                 week: false,
                 like: false, 
                 new: false,
                 top: false,
                 recommend: false,
               },
    },
    {
        id: 4,
        title: 'Stels Adrenalin MD V010 (2025)',
        images: ['bicycle-4_1.jpg'],
        old_price: 52180,
        price: 44350,
        description: 'Основное преимущество модели Stels Adrenalin MD V010 (2025) — поведение на дороге. Размер колес 27,5 х 2,8 дюйма делает Adrenalin более устойчивым и управляемым, упрощая преодоление препятствий в сравнении с МТБ на стандартных 26-дюймовых колесах. При этом он маневреннее и динамичнее, чем велосипеды с 29-дюймовыми колесами. Такой размер стал оптимальным компромиссом для сочетания проходимости и маневренности.',
        tags: [],
        rating: 10,
        carousel: {
                 today: false, 
                 week: false,
                 like: false, 
                 new: false,
                 top: false,
                 recommend: false,
               },
    },
    {
        id: 5,
        title: 'Uvex Finale TEST',
        images: ['helmet-1_1.jpg','helmet-1_2.jpg'],
        old_price: 1000000,
        price: 16199,
        description: "Шлем Uvex с удлиненной затылочной частью и съемным козырьком обеспечивает надежную защиту во время катания по бездорожью. 20 вентиляционных отверстий гарантируют отличный воздухообмен для максимального комфорта, а технология FAS и система 3D IAS отвечают за точную посадку по голове. Размер можно регулировать с помощью поворотного кольца.",
        tags: [1,2],
        rating: 5,
        category: 2,
        carousel: {
                today: false,
                week: false,
                like: false,
                new: false,
                top: false,
                recommend: false,
               }, 
    },



]
    
